[package]
name    = "phonenumber"
version = "0.3.2+8.12.9"
edition = "2018"

authors = ["meh. <meh@1aim.com>"]
license = "Apache-2.0"

description = "Library for parsing, formatting and validating international phone numbers."
repository  = "https://github.com/1aim/rust-phonenumber"
keywords    = ["phonenumber", "phone", "number", "parser", "formatter"]
readme = "README.md"

[dependencies]
regex       = "1.4"
regex-syntax = "0.6"
regex-cache = "~0.2.1"
lazy_static = "1.4"
fnv         = "1.0"
thiserror   = "~1.0.21"
quick-xml   = "0.19"
itertools   = "0.9"
either      = "1.6"
nom         = "5.1"

serde        = "1.0"
serde_derive = "1.0"
bincode      = "1.3"

[build-dependencies]
quick-xml    = "0.19"
thiserror    = "~1.0.21"
regex        = "1.4"
regex-syntax = "0.6"
serde        = "1.0"
serde_derive = "1.0"
bincode      = "1.3"

[dev-dependencies]
doc-comment  = "0.3"
criterion = "0.3"

[[bench]]
name = "init"
harness = false